### ISSUE TITLE
OSError running on windows 10

### ISSUE THREAD

**Issue by MadsMohr** [WISDEM/pyMAP#1]
Hi,

I am trying to use pyMAP on windows 10 (64bit), however running main gives following mistake:
"OSError: exception: access violation reading 0x0000000000000000"

i have installed pyMAP running "setup.py" after installing Microsoft Visual C++ build tools.
I looks like it successful compiles.

As i have understand through various searches, this is related to running compiled code on windows. Others report (Not for pyMAP specifically but other C programs executed through a python wrapper) that depending on Python version, Windows version and 32bit/64bit this might be or not be a problem. 

I have tried installing anaconda in both 32 and 64 bit version, and i both versions created environments with different versions of Python(3.7/3.6/2.7) . However, it still does not work.

This is the full message i get:

Traceback (most recent call last):

  File "C:\Users\mmm\OneDrive\Documents\Dutten\Kandidat\Speciale\PyMap\test\main.py", line 51, in <module>
    mooring_1.init( )

  File "C:\Users\mmm\AppData\Local\Continuum\anaconda3\lib\site-packages\pymap-1.0.0-py3.7-win-amd64.egg\pymap\pymap.py", line 303, in init
    libexec.map_init( self.f_type_init, self.f_type_u, self.f_type_p, self.f_type_x, self.f_type_z, self.f_type_d, self.f_type_y, self.f_type_initout, pointer(self.ierr), self.status )

OSError: exception: access violation reading 0x0000000000000000

This points to this piece of code:

    def init( self ):
        libexec.map_init( self.f_type_init, self.f_type_u, self.f_type_p, self.f_type_x, self.f_type_z, self.f_type_d, self.f_type_y, self.f_type_initout, pointer(self.ierr), self.status )
        if self.ierr.value != 0 : print(self.status.value)

Any help on this would be appropriated greatly.

Mads Mohr Madsen,
Msc student doing master thesis at DTU Wind Energy.

**Comment by gbarter** [comment]
Hi Mads,

The error seemed to be in the file reading module, which was using some very old python conventions.  I have updated this and tested it on my Windows 10 machine.

FYI: We have had loads of trouble with the MS C++ tools and more luck with the conda package combination of "m2w64-toolchain libpython" (on Windows).  If you are still having trouble, you might give those a shot.

Cheers,
Garrett

**Comment by MadsMohr** [comment]
Hi Garrett,

Thanks a lot for the fast response. After installing the new version i seem to have no problems.
Much appreciated! 

Best,
Mads
