### ISSUE TITLE
Installing pyMAP on Windows 

### ISSUE THREAD

**Issue by MaximilienAndre** [WISDEM/pyMAP#3]
Dear all, I have had issues when installing pyMAP, I wanted to leave a trace of how I solved it here if it may help people in the future. 

First I had to use the  dev branch.

Second I had to set this lines in setup.py 

```
from setuptools import setup, Extension
# from numpy.distutils.core import setup, Extension
```
It seemed that numpy.distutils was deprecated after python 3.10 

Third I had trouble when installing using : 

`$ python setup.py install`

I had an issue when runnning 

`from pymap import pyMAP `

saying that it could not find the name pyMAP in module pymap, so instead I reinstalled it using 

`pip install -e .`

from the pymap folder. 

With this fixes, I could run the exemples 1 and 2 smoothly.

**Comment by ebranlard** [comment]
Hi, 

Thanks for pointing that out, it makes sense. 
Do you think you could push a pull request to dev with your changes, including a change to the README.md to add the pip install? 

Thanks a lot!

**Comment by MaximilienAndre** [comment]
Dear Emmanuel, 

I have made a pull request with the modifications I mentionned, however I could not reproduce the first error I had when running 

`$ python setup.py install`

And instead I found that both this and `pip install -e .` were working. 

Best, 

Maximilien
